version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      dockerfile: "./api.dockerfile"
      context: "."
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  mongodb:
    build :
      dockerfile: "./mongo.dockerfile"
      context: "."
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped