version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    ports:
      - "8080:8080"
    environment:
      - ENV=cont
      - MONGO_API_USER
      - MONGO_API_PASSWORD
    # volumes:
    #   - ./app:/app
    #   - ./static:/static

  mongodb:
    build :
      dockerfile: "./mongo.dockerfile"
      context: "."
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_API_USER
      - MONGO_API_PASSWORD
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/:ro
